/*
 * Copyright (c) 2011-2018, The DART development contributors
 * All rights reserved.
 *
 * The list of contributors can be found at:
 *   https://github.com/dartsim/dart/blob/master/LICENSE
 *
 * This file is provided under the following "BSD-style" License:
 *   Redistribution and use in source and binary forms, with or
 *   without modification, are permitted provided that the following
 *   conditions are met:
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 *   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 *   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 *   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 *   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 *   AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *   ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *   POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Copyright (C) 2016 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef RESOURCES_H_
#define RESOURCES_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t RESOURCES_PACKAGE[];
    extern const int RESOURCES_PACKAGE_SIZE;
}

#define RESOURCES_SUZANNE_OFFSET 0
#define RESOURCES_SUZANNE_SIZE 272768
#define RESOURCES_SUZANNE_DATA (RESOURCES_PACKAGE + RESOURCES_SUZANNE_OFFSET)
#define RESOURCES_BAKEDCOLOR_OFFSET 272768
#define RESOURCES_BAKEDCOLOR_SIZE 40882
#define RESOURCES_BAKEDCOLOR_DATA (RESOURCES_PACKAGE + RESOURCES_BAKEDCOLOR_OFFSET)
#define RESOURCES_BAKEDTEXTURE_OFFSET 313650
#define RESOURCES_BAKEDTEXTURE_SIZE 41767
#define RESOURCES_BAKEDTEXTURE_DATA (RESOURCES_PACKAGE + RESOURCES_BAKEDTEXTURE_OFFSET)
#define RESOURCES_AOPREVIEW_OFFSET 355417
#define RESOURCES_AOPREVIEW_SIZE 43040
#define RESOURCES_AOPREVIEW_DATA (RESOURCES_PACKAGE + RESOURCES_AOPREVIEW_OFFSET)
#define RESOURCES_AIDEFAULTMAT_OFFSET 398457
#define RESOURCES_AIDEFAULTMAT_SIZE 202472
#define RESOURCES_AIDEFAULTMAT_DATA (RESOURCES_PACKAGE + RESOURCES_AIDEFAULTMAT_OFFSET)
#define RESOURCES_AIDEFAULTTRANS_OFFSET 600929
#define RESOURCES_AIDEFAULTTRANS_SIZE 201827
#define RESOURCES_AIDEFAULTTRANS_DATA (RESOURCES_PACKAGE + RESOURCES_AIDEFAULTTRANS_OFFSET)
#define RESOURCES_DEPTHVISUALIZER_OFFSET 802756
#define RESOURCES_DEPTHVISUALIZER_SIZE 40675
#define RESOURCES_DEPTHVISUALIZER_DATA (RESOURCES_PACKAGE + RESOURCES_DEPTHVISUALIZER_OFFSET)
#define RESOURCES_GROUNDSHADOW_OFFSET 843431
#define RESOURCES_GROUNDSHADOW_SIZE 73754
#define RESOURCES_GROUNDSHADOW_DATA (RESOURCES_PACKAGE + RESOURCES_GROUNDSHADOW_OFFSET)
#define RESOURCES_SANDBOXCLOTH_OFFSET 917185
#define RESOURCES_SANDBOXCLOTH_SIZE 198468
#define RESOURCES_SANDBOXCLOTH_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXCLOTH_OFFSET)
#define RESOURCES_SANDBOXLIT_OFFSET 1115653
#define RESOURCES_SANDBOXLIT_SIZE 233959
#define RESOURCES_SANDBOXLIT_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLIT_OFFSET)
#define RESOURCES_SANDBOXLITFADE_OFFSET 1349612
#define RESOURCES_SANDBOXLITFADE_SIZE 237378
#define RESOURCES_SANDBOXLITFADE_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLITFADE_OFFSET)
#define RESOURCES_SANDBOXLITTRANSPARENT_OFFSET 1586990
#define RESOURCES_SANDBOXLITTRANSPARENT_SIZE 235423
#define RESOURCES_SANDBOXLITTRANSPARENT_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLITTRANSPARENT_OFFSET)
#define RESOURCES_SANDBOXSPECGLOSS_OFFSET 1822413
#define RESOURCES_SANDBOXSPECGLOSS_SIZE 233465
#define RESOURCES_SANDBOXSPECGLOSS_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXSPECGLOSS_OFFSET)
#define RESOURCES_SANDBOXSUBSURFACE_OFFSET 2055878
#define RESOURCES_SANDBOXSUBSURFACE_SIZE 207794
#define RESOURCES_SANDBOXSUBSURFACE_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXSUBSURFACE_OFFSET)
#define RESOURCES_SANDBOXUNLIT_OFFSET 2263672
#define RESOURCES_SANDBOXUNLIT_SIZE 40821
#define RESOURCES_SANDBOXUNLIT_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXUNLIT_OFFSET)
#define RESOURCES_TEXTUREDLIT_OFFSET 2304493
#define RESOURCES_TEXTUREDLIT_SIZE 225713
#define RESOURCES_TEXTUREDLIT_DATA (RESOURCES_PACKAGE + RESOURCES_TEXTUREDLIT_OFFSET)
#define RESOURCES_TRANSPARENTCOLOR_OFFSET 2530206
#define RESOURCES_TRANSPARENTCOLOR_SIZE 40714
#define RESOURCES_TRANSPARENTCOLOR_DATA (RESOURCES_PACKAGE + RESOURCES_TRANSPARENTCOLOR_OFFSET)

#endif
