FROM archlinux:latest

# Install essential packages
RUN sudo pacman -Syu --needed --noconfirm \
  lsb-release

# Change user to 'docker', which is set by greyltc/archlinux-aur
# because yay prevent running with sudo/root.
#USER docker

#ENTRYPOINT bash
